spring.application.name=Dev-archive

spring.datasource.url=jdbc:mysql://localhost:3306/dev_archive?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=291410

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true